### ISSUE TITLE
Favorites button is glitchy

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-web#132]
## Expected

- Filled in star when marked as favorite
- Star border when not marked as favorite

## Actual

- Star border when marked as favorite
- Star is missing when not marked as favorite

![image](https://user-images.githubusercontent.com/2477952/166964821-93506fda-3568-4cee-88d9-fa2e99323bda.png)

^ TestRepo is marked as favorite, and hello-world is not.

**Comment by Alexamakans** [comment]
Caused by upgrade to PrimeNG v13.3.3.

In v12 it is `pi-star` for filled, `pi-star-o` for bordered/outlined.
In v12 it is `pi-star-fill` for filled, `pi-star` for bordered/outlined.

For favorites button this would need to be changed in the `getClass` method of `src/app/projects/project-favorite/project-favorite-button.component.ts`.

Additionally, some redundant variants like `pi-file-o`, which is equivalent to `pi-file` even in v12, have been removed.
We seem to have used `pi-file-o`, so this would need to be changed to `pi-file` as well.

The regex `\bpi-\w+?\b` should find all uses of these icons.
Will probably need to be compared between v12 and v13 using the lists below to determine the one that was in place earlier.
[v12 icon list](https://www.primefaces.org/primeng-v12-lts/#/icons)
[v13 icon list](https://www.primefaces.org/primeng/icons)
